version: "2"
services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - "7006:3306"
    environment:
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mysql_data:/var/lib/mysql
volumes:
  mysql_data: